---
pool:
  name: default
  vmimage: "ubuntu-latest"

trigger:
- main

- task: Maven@3
  inputs:
    mavenPOMFile: 'pom.xml'
    goals: 'package'
    javaHomeOption: 'path'
    mavenVersionOption: 'path'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    jdkVersionOption: '1.17'
    jdkArchitectureOption: 'x64'
    jdkdirectory: /usr/lib/jvm/java-17-openjdk-amd64
    mavenDirectory: /opt/maven
